device:
  layer: rpi4
  hostname: gateway-pi4-dev
  user1: gateway
  user1sudo: nopasswd

image:
  layer: image-rpios
  name: gateway-trixie-pi4-headless
  boot_part_size: 200%
  root_part_size: 300%

layer:
  gateway: gateway-base

locale:
  timezone: Asia/Karachi
  default: en_US.UTF-8
  keyboard_layout: English (US)
  keyboard_keymap: us

ssh:
  pubkey_user1: /home/hsb/.ssh/id_ed25519.pub
  pubkey_only: y
